name: build_unittest

on: [push]

jobs:
  build-windows-cmake:
    name: Windows-CMake
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: configure
      run: |
        ls env:
        mkdir target
        cd target
        cmake .. -DCMAKE_INSTALL_PREFIX=installWindowsCMake-Github -DPYTHON_VERSION="3.7"
    - name: build
      run: |
        cd target
        cmake --build . --config Release -j
    - name: install
      run: |
        cd target
        cmake --build . --config Release --target install
    - name: test
      run: |
        cd target
        ctest -C Release


  build-linux-cmake:
    name: Linux-CMake
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: configure
      run: |
        env
        which python
        mkdir target
        cd target
        cmake .. -DCMAKE_INSTALL_PREFIX=installLinuxCMake-Github -DPYTHON_VERSION=3.7
    - name: build
      run: |
        cd target
        cmake --build . -j
    - name: install
      run: |
        cd target
        cmake --build . --target install
    - name: test
      run: |
        cd target
        ctest


  build-windows-waf:
    name: Windows-waf
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: configure
      run: |
        pip install numpy
        mkdir installWindowsWaf-Github
        python waf configure --prefix="$PWD/installWindowsWaf-Github"
    - name: build
      run: |
        python waf build
    - name: install
      run: |
        python waf install
    - name: test
      run: |
        python waf install --alltests

  build-linux-waf:
    name: Linux-waf
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: configure
      run: |
        pip install numpy
        mkdir installLinuxWaf-Github
        python waf configure --prefix="$PWD/installLinuxWaf-Github"
    - name: build
      run: |
        python waf build
    - name: install
      run: |
        python waf install
    - name: test
      run: |
        python waf install --alltests
